version: '3.8'

services:
  xinference:
    build:
      context: ../../../
      dockerfile: /xinference/deploy/docker/Dockerfile
      extra_hosts: 
        - "raw.githubusercontent.com:185.199.108.133"
    image: gongjiaing/xinference
    # image: xprobe/xinference:latest
    container_name: xinference
    ports:
      - "${HOST_UI_PORT}:${CONTAINER_UI_PORT}"
#    volumes:
#      # Replace <xinference_home> with your xinference home path on the host machine
#      - <xinference_home>:/root/.xinference
#      # Replace <huggingface_cache_dir> with your huggingface cache path, default is
#      # <home_path>/.cache/huggingface
#      - <huggingface_cache_dir>:/root/.cache/huggingface
#      # If models are downloaded from modelscope, replace <huggingface_cache_dir> with
#      # your modelscope cache path, default is <home_path>/.cache/modelscope
#      - <modelscope_cache_dir>:/root/.cache/modelscope
#    environment:
#      # add envs here. Here's an example, if you want to download model from modelscope
#      - XINFERENCE_MODEL_SRC=modelscope
    environment:
      - XINFERENCE_HOME=${CONTAINER_MODEL_DIR}
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    command: xinference-local --host 0.0.0.0 --port ${CONTAINER_UI_PORT}
    volumes:
      - ${HOST_MODEL_DIR}:${CONTAINER_MODEL_DIR}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: all
